# Generated by Django 6.0.6 on 2026-07-22 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(max_length=50, verbose_name='Número de Expediente')),
                ('tipo_juicio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Tipo de Juicio')),
                ('partes', models.CharField(blank=True, max_length=255, null=True, verbose_name='Partes (Actor vs Demandado)')),
                ('ultima_revision_scraper', models.DateField(blank=True, null=True, verbose_name='Última Consulta al Boletín')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
            },
        ),
        migrations.CreateModel(
            name='Juzgado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_boletin', models.CharField(max_length=20, unique=True, verbose_name='ID en el Boletín')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Juzgado')),
                ('materia', models.CharField(choices=[('familiar', 'Familiar'), ('civil', 'Civil'), ('mercantil', 'Mercantil'), ('laboral', 'Laboral'), ('penal', 'Penal'), ('control', 'Control y Oralidad'), ('mixto', 'Mixto')], max_length=50, verbose_name='Materia / Contexto')),
                ('partido_judicial', models.CharField(default='Primer Partido Judicial', help_text='Jurisdicción territorial del juzgado (Ej: Primer Partido Judicial para la Zona Metropolitana)', max_length=100, verbose_name='Partido Judicial')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Vigente en el Boletín')),
            ],
            options={
                'verbose_name': 'Juzgado',
                'verbose_name_plural': 'Juzgados',
                'ordering': ['materia', 'id_boletin'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(help_text='Incluir código de país sin signo + (Ej: 52133XXXXXXXX)', max_length=20, unique=True, verbose_name='Teléfono (WhatsApp)')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Usuario Activo')),
                ('notificaciones_activas', models.BooleanField(default=True, verbose_name='Notificaciones Habilitadas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es Staff (Admin)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo en Sistema')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Acuerdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acuerdo', models.DateField(db_index=True, verbose_name='Fecha de Acuerdo')),
                ('fecha_promocion', models.DateField(blank=True, null=True, verbose_name='Fecha de Promoción')),
                ('texto', models.TextField(verbose_name='Texto del Acuerdo')),
                ('procesado_para_notificacion', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acuerdos', to='boletin.expediente')),
            ],
            options={
                'verbose_name': 'Acuerdo',
                'verbose_name_plural': 'Acuerdos',
                'ordering': ['-fecha_acuerdo', '-created_at'],
                'unique_together': {('expediente', 'fecha_acuerdo', 'texto')},
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='juzgado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedientes', to='boletin.juzgado'),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('fallido', 'Fallido'), ('leido', 'Leído')], default='pendiente', max_length=20)),
                ('mensaje_enviado', models.TextField(blank=True, null=True, verbose_name='Contenido del Mensaje')),
                ('fecha_intento', models.DateTimeField(auto_now_add=True)),
                ('acuerdo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='boletin.acuerdo')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de Notificación',
                'verbose_name_plural': 'Bitácoras de Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suscrito_el', models.DateTimeField(auto_now_add=True)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletin.expediente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suscripción',
                'verbose_name_plural': 'Suscripciones',
                'unique_together': {('usuario', 'expediente')},
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='usuarios',
            field=models.ManyToManyField(related_name='expedientes_suscritos', through='boletin.Suscripcion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expediente',
            index=models.Index(fields=['numero_expediente'], name='boletin_exp_numero__12c2f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expediente',
            unique_together={('juzgado', 'numero_expediente')},
        ),
    ]
