# Generated by Django 6.0.6 on 2026-07-23 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_seed_juzgados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos/%Y/%m/', verbose_name='Archivo Adjunto')),
                ('nombre_archivo', models.CharField(blank=True, max_length=255, verbose_name='Nombre Original')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acuerdo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='boletin.acuerdo')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='boletin.expediente')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
            },
        ),
    ]
