# Generated by Django 6.0.6 on 2026-06-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_seed_juzgados'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acuerdo',
            options={'ordering': ['-fecha_acuerdo', '-created_at'], 'verbose_name': 'Acuerdo', 'verbose_name_plural': 'Acuerdos'},
        ),
        migrations.AlterUniqueTogether(
            name='acuerdo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='fecha_acuerdo',
            field=models.DateField(db_index=True, default='2026-06-16', verbose_name='Fecha de Acuerdo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acuerdo',
            name='fecha_promocion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Promoción'),
        ),
        migrations.RemoveField(
            model_name='acuerdo',
            name='fecha_publicacion',
        ),
    ]
