# Generated by Django 6.0.6 on 2026-06-17 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0003_alter_acuerdo_options_alter_acuerdo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='acuerdo',
            unique_together={('expediente', 'fecha_acuerdo', 'texto')},
        ),
    ]
