# Generated by Django 6.0.6 on 2026-07-24 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0003_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
