# Generated by Django 6.0.6 on 2026-07-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0004_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
