# Generated by Django 6.0.6 on 2026-06-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0004_alter_acuerdo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='ultima_revision_scraper',
            field=models.DateField(blank=True, null=True, verbose_name='Última Consulta al Boletín'),
        ),
    ]
