# Generated by Django 6.0.6 on 2026-07-24 04:45

import boletin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0005_usuario_email_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=boletin.models.user_directory_path),
        ),
    ]
