# Generated by Django 6.0.6 on 2026-07-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0006_alter_usuario_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='suscripcion',
            name='estatus',
            field=models.CharField(choices=[('activa', 'Activa'), ('bloqueada', 'Bloqueada')], default='activa', max_length=20),
        ),
    ]
