# Generated by Django 6.0.6 on 2026-07-31 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0007_suscripcion_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_creados', to=settings.AUTH_USER_MODEL),
        ),
    ]
